Sql:
  Host: "infra-de-1.mio.wtf"
  Port: "3306"
  Database: "s10_daddy"
  Username: "u10_IuGNoCN709"
  Password: "PNy8KjiCLQ5U+JL@B+qRyyV."

Settings:
  Prefix: "§8▏ &#face87Tidy-Vanilla §8» §7"
  BanCommand: "ban %player% You have lost all your hearts 24h"